/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VesselsRouteImport } from './routes/vessels'
import { Route as ChartOfAccountsRouteImport } from './routes/chart-of-accounts'
import { Route as AuditTrailRouteImport } from './routes/audit-trail'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VesselsRoute = VesselsRouteImport.update({
  id: '/vessels',
  path: '/vessels',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartOfAccountsRoute = ChartOfAccountsRouteImport.update({
  id: '/chart-of-accounts',
  path: '/chart-of-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTrailRoute = AuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit-trail': typeof AuditTrailRoute
  '/chart-of-accounts': typeof ChartOfAccountsRoute
  '/vessels': typeof VesselsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit-trail': typeof AuditTrailRoute
  '/chart-of-accounts': typeof ChartOfAccountsRoute
  '/vessels': typeof VesselsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit-trail': typeof AuditTrailRoute
  '/chart-of-accounts': typeof ChartOfAccountsRoute
  '/vessels': typeof VesselsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/audit-trail' | '/chart-of-accounts' | '/vessels'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/audit-trail' | '/chart-of-accounts' | '/vessels'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit-trail'
    | '/chart-of-accounts'
    | '/vessels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditTrailRoute: typeof AuditTrailRoute
  ChartOfAccountsRoute: typeof ChartOfAccountsRoute
  VesselsRoute: typeof VesselsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vessels': {
      id: '/vessels'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof VesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-of-accounts': {
      id: '/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/chart-of-accounts'
      preLoaderRoute: typeof ChartOfAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-trail': {
      id: '/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditTrailRoute: AuditTrailRoute,
  ChartOfAccountsRoute: ChartOfAccountsRoute,
  VesselsRoute: VesselsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
